# Generated by Django 5.0.6 on 2024-06-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company_remove_user_phone_number_user_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_user', 'Может изменять текст для рассылок')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
