# Generated by Django 5.0.6 on 2024-06-01 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingattempt',
            name='mailing',
        ),
        migrations.AddField(
            model_name='mailing',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.client'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='last_attempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailingattempt'),
        ),
    ]
