# Generated by Django 5.0.6 on 2024-06-04 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_rename_is_active_mailing_status_of_mailing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status_of_mailing',
            field=models.CharField(choices=[('Создана', 'Создана'), ('В работе', 'В работе'), ('Завершена', 'Завершена'), ('Ошибка отправки', 'Ошибка отправки')], default='Создана', verbose_name='Состояние рассылки'),
        ),
    ]
