# Generated by Django 5.0.6 on 2024-06-04 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_mailing_owner_alter_mailing_status_of_mailing'),
        ('users', '0002_company_remove_user_phone_number_user_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingtext',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company', verbose_name='Компания'),
        ),
    ]
