# Generated by Django 5.0.6 on 2024-06-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_mailingtext_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Конфиг_письма', 'verbose_name_plural': 'Конфиг_письма'},
        ),
    ]
