# Generated by Django 5.0.6 on 2024-06-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_status_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='last_attempt_status',
        ),
    ]
