# Generated by Django 5.0.6 on 2024-06-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_rename_status_status_last_attempt_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='answer',
            new_name='is_active',
        ),
    ]
