# Generated by Django 5.0.6 on 2024-06-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_rename_answer_mailing_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_edit_is_active', 'edit is active')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
