# Generated by Django 5.0.6 on 2024-06-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0013_alter_client_options_alter_mailing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_all_mailing', 'Может видеть все рассылки'), ('can_disable_mailing', 'Может отключать рассылки'), ('cannot_change_mailing', 'Не может изменять рассылки'), ('cannot_delete_mailing', 'Не может удалять рассылки'), ('cannot_create_mailing', 'Не может создавать рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingtext',
            options={'permissions': [('can_change_mailingtext_list', 'Может изменять текст для рассылок')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
    ]
