# Generated by Django 5.0.6 on 2024-06-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0014_alter_mailing_options_alter_mailingtext_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',), 'permissions': [('can_view_client_list', 'Может просматривать пользователей сервиса')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
