# Generated by Django 5.0.6 on 2024-06-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0016_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_mailing', 'Может видеть все рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
