# Generated by Django 5.0.6 on 2024-06-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0017_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
