# Generated by Django 5.0.6 on 2024-06-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0018_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_mailing', 'Может видеть все рассылки'), ('can_disable_mailing', 'Может отключать рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
